#!/usr/bin/env bash
# Print a markdown index of all specs (stdout). `make spec-index` writes it to specs/INDEX.md.
set -u
. "$(dirname "$0")/_lib.sh"
cd "$ROOT"
echo "# Spec index"
echo
echo "_Generated by \`make spec-index\` on $(date +%F). Do not edit by hand._"
for dir in 00-product 01-architecture 02-features 03-contracts 04-decisions; do
  echo; echo "## $dir"; echo
  echo "| ID | Title | Status | Reviewed | File |"; echo "| --- | --- | --- | --- | --- |"
  for s in $(spec_files | grep "/specs/$dir/"); do
    rel="${s#$ROOT/}"
    printf '| %s | %s | `%s` | %s | [%s](%s) |\n' "$(fm_get "$s" id)" "$(fm_get "$s" title)" "$(fm_get "$s" status)" "$(fm_get "$s" last_reviewed)" "${rel#specs/}" "${rel#specs/}"
  done
done
echo
oq="$(grep -c '^### Q' specs/OPEN-QUESTIONS.md 2>/dev/null)"
echo "Open questions: ${oq:-0} — see [OPEN-QUESTIONS.md](OPEN-QUESTIONS.md). Roadmap: [ROADMAP.md](ROADMAP.md)."
